// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqkqfgepcpkjenwnogob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxa3FmZ2VwY3BramVud25vZ29iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDQwMTYsImV4cCI6MjA2NjQyMDAxNn0.xp95YVebsO5OPXjtbc3E3Cdq-m4cINE-3vurd-Guhoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);